#!/bin/sh

set -e

echo "Starting modulairy php-fpm-apache container"

cd /var/www/localhost/htdocs

if [ ! -z "$GIT_REPOSITORY_URL" ]
then
      echo "git clone from $GIT_REPOSITORY_URL"
      rm -rf * && git clone $GIT_REPOSITORY_URL .
        if [ ! -z "$GIT_BRANCH" ]
        then
            echo "Checkout $GIT_BRANCH branch"
            git checkout $GIT_BRANCH
        fi
fi

# exec php-fpm &
#exec httpd -DFOREGROUND "$@" &
echo Starting php-fpm...
php-fpm &
echo Started php-fpm...

echo Starting nginx...
nginx -g 'daemon off;' &
echo Started nginx


wait -n
echo Closing...
exit $?