#!/bin/sh

set -e

echo "Starting modulairy php-fpm-apache container"

cd /var/www/localhost/htdocs

if [ ! -z "$GIT_REPOSITORY_URL" ]
then
      echo "git clone from $GIT_REPOSITORY_URL"
      rm -rf * && git clone $GIT_REPOSITORY_URL .
        if [ ! -z "$GIT_BRANCH" ]
        then
            echo "Checkout $GIT_BRANCH branch"
            git checkout $GIT_BRANCH
        fi
fi

if [ ! -z "$INIT_SCRIPT" ]
then
    cd /
    echo $INIT_SCRIPT > initialize.sh 
    chmod +x /initialize.sh

    echo "running initialize script..."
    bash /initialize.sh
    cd /var/www
fi

echo Starting php-fpm...
php-fpm &
echo Started php-fpm...

echo Starting nginx...
nginx -g 'daemon off;' &
echo Started nginx


wait
echo Closing...
exit $?
